title: Launching Github Web Page
author: Wendel Viana Lima
email: wchristofer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My firsts steps with Github Pages!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  lima-wendel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
